<pre class='metadata'>
Title: Health-RI Metadata Model
Shortname: Hri-spec
status: iso/TS
level: none
TR: https://w3id.org/health-ri/metadata/releases/latest
URL: https://health-ri.github.io/metadata-documentation/
Previous Version: https://w3id.org/health-ri/metadata/releases
Status Text: Draft for the forthcoming minor release; version and date pending.
Repository: w3id.org/health-ri/metadata/git
Editor: Bruna dos Santos Vieira
Former Editor: Inês de Oliveira Coelho Henriques
Former Editor: César Bernabé
Editor: Kees Burger
Former Editor: Patrick Dekker
Editor: Joost Daams
Former Editor:
Former Editor: Milou de Jong
Editor: Ana Konrad
Editor: Hannah Neikes
Editor: ⁠Reinier Groeneveld
Editor: Niek van Ulzen
Editor: Pedro Paulo F. Barcelos
Former Editor: Dena Tahvildari
Former Editor: Xiaofeng Liao
Former Editor: Mark Janse
Former Editor: Junda Huang
Former Editor: Luiz Bonino
Issue Tracking: Report a bug https://github.com/Health-RI/health-ri-metadata/blob/develop/CONTRIBUTING.md#i-want-to-report-a-bug
Issue Tracking: Open new issues https://github.com/Health-RI/health-ri-metadata/issues/new
Issue Tracking: Status reported issues https://github.com/Health-RI/health-ri-metadata/issues
Logo: health-ri logo
!License: CC-BY-4.0
Boilerplate: copyright no, conformance off, references off
Max ToC Depth: 4
Abstract: <img src="https://raw.githubusercontent.com/Health-RI/metadata-documentation/main/src/images/HRI_Logo.png" alt="Health-RI Logo" title="Health-RI Logo" width="300"> <br/> The National Health Data Catalogue uses a core metadata schema: a set of minimal elements for describing each resource (e.g. dataset) with common metadata. It defines the requirements to access and reuse information across Health-RI nodes via the National Catalogue. This document contains the specification details on the Health-RI core metadata schema. 
Markup Shorthands: markdown yes, css no
</pre>

<pre class=include>
path: src/table/style-tables-general.md
</pre>

<pre class=include>
path: src/chapter/3-purpose-and-audience.md
</pre>

<pre class=include>
path: src/chapter/4-introduction.md
</pre>

<pre class=include>
path: src/chapter/11-next-release.md
</pre>

<pre class=include>
path: src/chapter/1-permanent-urls.md
</pre>

<pre class=include>
path: src/chapter/5-classtext.md
</pre>

<pre class=include>
path: src/chapter/6-classes-main.md
</pre>

<pre class=include>
path: src/chapter/7-classes-supportive.md
</pre>

<pre class=include>
path: src/chapter/10-controlled-vocabularies.md
</pre>
